-- MySQL Script generated by MySQL Workbench
-- Tue Dec 10 17:38:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema www
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema www
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `www` DEFAULT CHARACTER SET utf8 ;
USE `www` ;

-- -----------------------------------------------------
-- Table `www`.`Vyrobce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `www`.`Vyrobce` ;

CREATE TABLE IF NOT EXISTS `www`.`Vyrobce` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nazev` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `www`.`Produkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `www`.`Produkt` ;

CREATE TABLE IF NOT EXISTS `www`.`Produkt` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nazev` VARCHAR(50) NOT NULL,
  `Popis` VARCHAR(2000) NULL,
  `Cena` DECIMAL(2) NOT NULL,
  `Skladem` BINARY(1) NOT NULL,
  `Vyrobce_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Vyrobce_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Produkt_Vyrobce1_idx` (`Vyrobce_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Produkt_Vyrobce1`
    FOREIGN KEY (`Vyrobce_ID`)
    REFERENCES `www`.`Vyrobce` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `www`.`Platba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `www`.`Platba` ;

CREATE TABLE IF NOT EXISTS `www`.`Platba` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nazev` VARCHAR(50) NOT NULL,
  `Popis` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `www`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `www`.`Role` ;

CREATE TABLE IF NOT EXISTS `www`.`Role` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nazev` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `www`.`Uzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `www`.`Uzivatel` ;

CREATE TABLE IF NOT EXISTS `www`.`Uzivatel` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Jmeno` VARCHAR(100) NOT NULL,
  `Prijmeni` VARCHAR(100) NOT NULL,
  `DatumNarozeni` DATE NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `SECRET` VARCHAR(64) NOT NULL,
  `Role_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Role_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Uzivatel_Role_idx` (`Role_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Uzivatel_Role`
    FOREIGN KEY (`Role_ID`)
    REFERENCES `www`.`Role` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `www`.`Doprava`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `www`.`Doprava` ;

CREATE TABLE IF NOT EXISTS `www`.`Doprava` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nazev` VARCHAR(50) NOT NULL,
  `Popis` VARCHAR(2000) NULL,
  `Cena` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `www`.`Objednavka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `www`.`Objednavka` ;

CREATE TABLE IF NOT EXISTS `www`.`Objednavka` (
  `ID` INT NOT NULL,
  `CelkovaCena` DECIMAL(2) NOT NULL,
  `DatumVytvoreni` DATE NOT NULL,
  `DatumVystaveni` DATE NOT NULL,
  `Zaplaceno` BINARY(1) NOT NULL,
  `DatumPlatby` DATE NOT NULL,
  `Uzivatel_ID` INT NOT NULL,
  `Doprava_ID` INT NOT NULL,
  `Platba_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Doprava_ID`, `Platba_ID`),
  INDEX `fk_Objednavka_Uzivatel1_idx` (`Uzivatel_ID` ASC) VISIBLE,
  INDEX `fk_Objednavka_Doprava1_idx` (`Doprava_ID` ASC) VISIBLE,
  INDEX `fk_Objednavka_Platba1_idx` (`Platba_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Objednavka_Uzivatel1`
    FOREIGN KEY (`Uzivatel_ID`)
    REFERENCES `www`.`Uzivatel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Objednavka_Doprava1`
    FOREIGN KEY (`Doprava_ID`)
    REFERENCES `www`.`Doprava` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Objednavka_Platba1`
    FOREIGN KEY (`Platba_ID`)
    REFERENCES `www`.`Platba` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `www`.`rel_Objednavka_Produkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `www`.`rel_Objednavka_Produkt` ;

CREATE TABLE IF NOT EXISTS `www`.`rel_Objednavka_Produkt` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Kusu` INT NOT NULL,
  `Objednavka_ID` INT NOT NULL,
  `Produkt_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Objednavka_ID`, `Produkt_ID`),
  INDEX `fk_rel_Objednavka_Produkt_Produkt1_idx` (`Produkt_ID` ASC) VISIBLE,
  CONSTRAINT `fk_rel_Objednavka_Produkt_Objednavka1`
    FOREIGN KEY (`Objednavka_ID`)
    REFERENCES `www`.`Objednavka` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rel_Objednavka_Produkt_Produkt1`
    FOREIGN KEY (`Produkt_ID`)
    REFERENCES `www`.`Produkt` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
